### ISSUE TITLE
Rails 6 support

### ISSUE THREAD

**Issue by dkam** [opal/opal-rails#108]
Hey guys, 
    Is there an ETA for Rails 6 support? 
Cheers,

**Comment by elia** [comment]
Support via webpacker is already covered by https://www.npmjs.com/package/opal-webpack-loader (thanks to @janbiedermann) and we're working toward making it official. I'll add a note on the readme referencing it, since with Rails 6 that's the official way to deal with JS.

**Comment by elia** [comment]
@dkam I just released opal-rails v1.0.1 with Rails 6 support (for sprockets).
