### ISSUE TITLE
Rails 6.1 support

### ISSUE THREAD

**Issue by wintersolutions** [opal/opal-rails#120]
Hi, is support for Rails >= 6.1 planned?

**Comment by Atelier-Mirai** [comment]
Me too.
Please support Ruby 3.0 & Rails 6.1.

**Comment by hmdne** [comment]
The support is there - for all Ruby 3.0, 3.1 (when Rails release their point release or you use the git branch), Rails 6.1 and Rails 7.0

**Comment by elia** [comment]
opal-rails v2.0.2 allowing Rails 7 is out! https://rubygems.org/gems/opal-rails/versions/2.0.2
Thanks for the patience 😊
