### ISSUE TITLE
Custom asset directory

### ISSUE THREAD

**Issue by aantix** [opal/opal-rails#18]
I created a custom asset directory (`lib/assets`).  

I added it to the rails asset paths in my `application.rb`.  

    config.assets.paths << "#{Rails.root}/lib/"

I have a class in that custom asset directory (`users.js.rb`).

This asset does not get included (`users.js.rb`) when serving up my pages.  

It does get included when the asset is located in `app/assets/javascripts`.  

Any idea as to why my `user.js.rb` class in my custom asset directory isn't being included?

**Comment by elia** [comment]
I'll close assuming it's not an issue anymore. Feel free to reopen/ping me if there's anything I can do.
