### ISSUE TITLE
Add support for JST

### ISSUE THREAD

**Issue by lloeki** [opal/opal-rails#25]
Javascript templates are great to create rich DOM structures client-side. Integrating them into opal-rails could turn this example:

```ruby
# app/views/posts/create.js.opal

post = Element.find('.post')
post.find('.title').html    = @post[:title]
post.find('.body').html     = @post[:body]
post.find('.comments').html = comments_html
```

into this:

```ruby
# app/views/posts/create.js.opal
post = Element.find('.posts')
post << render partial: 'post', { locals: { comments_html: comments_html }
```

```slim
# app/assets/javascripts/templates/posts/_post.jst.skim
.post
   .title = @post['title']
   .body = @post['body']
   .comments = comments_html
```

The latter file could be EJS, Skim or whatever, or even better straight up ERB, Haml or Slim (pending opal-erb and opal-slim implementation) thanks to Opal.

Basically this amounts to implementing:
- a `template` function that resolves the path to the template
- a `render` function that calls `JST[template(name)](locals)`

For reference, here is an excerpt of actual CoffeeScript code code that I have in a project:

```coffee
#= require_tree ./templates/bootstrap

jQuery ($) ->
    templates_root = 'templates/bootstrap'

    template = (name) -> "#{templates_root}/#{name}"

    $.extend bootstrap: {}
    $.extend $.bootstrap,
        dropdown: (title, items) ->
            JST[template 'dropdown'](title: title, items: items)

    $(document).ready ->
        $('.tooltip-trigger[data-title]').tooltip
            trigger: 'hover'
```

**Comment by elia** [comment]
I'll close, was open as a reminder to add more documentation. Lack of docs is a fruit hanging so low so visible we don't need no reminder. 

Of course any docs PR is pretty much guaranteed to be merged immediately 😻
