### ISSUE TITLE
Make specs for opal-rspec configurable

### ISSUE THREAD

**Issue by adambeynon** [opal/opal-rails#28]
@elia I have been trying to work out the best way for configuring where specs should be loaded from for the `opal_spec` route. What about a simple `config` option which the controller could use?

## Standard config

```ruby
# config/initializers/opal.rb
Rails.application.config.opal.rspec_path = Rails.root.join('app', 'assets', 'javascripts', 'spec')
```

Of course, the given path would already have to be in the sprockets/assets path.

## Custom/additional config

My main use for this is that I now share quite a lot of lib code between opal and rails, and I want to run the specs on it both client and server side. So maybe an array would be a better option:

```ruby
# config/initializers/opal.rb
Rails.application.config.opal.rspec_path # default path => "app/assets/javascripts/spec"
Rails.application.config.opal.rspec_path += Rails.root.join('spec', 'shared')
```

Again, any customization would require that given path to also be added to the sprockets pipeline.

```ruby
Rails.application.config.assets.paths << Rails.root.join('app', 'shared')
Rails.application.config.assets.paths << Rails.root.join('spec', 'shared')
```

I can implement this @elia, was just looking for your thoughts on it.

**Comment by elia** [comment]
There's now `config.opal.spec_location` that defaults to `spec-opal` (as in `Rails.root.join('spec-opal')`).

Feel free to reopen of course :wink:
