### ISSUE TITLE
using opal in HAML filter not working

### ISSUE THREAD

**Issue by cantonic** [opal/opal-rails#39]
when trying to use opal in a HAML filter like... 

```haml
#content
  Foobar

:opal
  Document.ready? do
    puts 'yay'
  end
```

... throws error in javascript console: `Uncaught ReferenceError: Opal is not defined`

in my `application.js` opal is required at the top.

using
- opal-rails 0.7.1
- rails 4.1.9
- ruby 2.2.0

**Comment by elia** [comment]
Ensure you're not using async on script tags

**Comment by elia** [comment]
is this still an issue?

**Comment by elia** [comment]
Closing, but feel free to ping me for this to be reopened

**Comment by josephschito** [comment]
Same error!
This is my application.rb.js file:

`require 'rails-ujs'
require 'activestorage'
require 'turbolinks'
require 'jquery3'
require 'popper'
require 'bootstrap-sprockets'
require_tree '.'`
