### ISSUE TITLE
No route matches [GET] "/javascripts/opal_spec_runner_xxx.js"

### ISSUE THREAD

**Issue by elia** [opal/opal-rails#45]
https://travis-ci.org/opal/opal-rails/jobs/56539509#L177-L180

This spec only fails on Travis:

```
  1) In-browser specs runner runs single spec file
     Failure/Error: Unable to find matching line from backtrace
     ActionController::RoutingError:
       No route matches [GET] "/javascripts/opal_spec_runner_b1ba865074f563388c5fbcd5c5dcc04276ab1dfd.js"
```

_Some context_
The asset is [built on the fly](https://github.com/opal/opal-rails/blob/master/app/controllers/opal_spec_controller.rb#L14) with a name based on its contents (just like sprockets digest), the contents varies depending on the specs required for a particular run and it's done to avoid two open spec pages trying to write the same file. the file's dirname is added to sprockets [at rails init time](https://github.com/opal/opal-rails/blob/master/lib/opal/rails/engine.rb#L26-L29).

@josh any idea on why it doesn't find the assets and sets `/javascripts/` as the prefix?

**Comment by josh** [comment]
Is /javascripts just supposed to be a serving path prefix or is that directory in the root of your load path?

**Comment by elia** [comment]
The prefix is the default "assets", but somehow the include tag calls it with the "javascripts" prefix. I wonder if it's the legacy helper that kicks in…

**Comment by josh** [comment]
Weird, any files under `public/` you think could trigger that?

**Comment by elia** [comment]
Closing, it's probably some issue with the travis file system
