### ISSUE TITLE
using import instead of sprockets statements does not work

### ISSUE THREAD

**Issue by jibi** [opal/opal-rails#48]
After creating a new rails project with

```
rails new o --javascript=opal
```
(after adding a new test controller and related route)

and renaming `application.js` to `application.js.rb` with the following content

```rb
#= require opal
#= require opal_ujs
#= require turbolinks
#= require_tree .

puts "test" 
```

everything just works.

But if I replace (as advised in the README) the application.js.rb with this

```rb
require 'opal'
require 'opal_ujs'
require 'turbolinks'
require_tree '.'

puts "test"
```
I get a RuntimeError

```
An error occurred while compiling: turbolinks

parse error on value "BEFORE_CHANGE" (tLABEL) :turbolinks:14
Source: turbolinks:14:16
  BEFORE_CHANGE:  'page:before-change'
~~~~~~~~~~~~~~~^
```
at the `javascript_include_tag` line

```html
  <title>O</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
```

am I doing something wrong or is this a bug?

**Comment by elia** [comment]
Which version are you using?

**Comment by jibi** [comment]
rails 4.2.1, opal 0.7.1 and opal-rails 0.7.0

**Comment by elia** [comment]
It's probably better to use normal sprockets requires for non Opal assets (as turbolinks) because 0.7 has some issues with them. 

I'll close the issue as I don't think it's worth updating the readme for a previous version (master is targeting Opal 0.8 which should be fine with the advised configuration)

But feel free to share any thoughts you have on the matter.

**Comment by jibi** [comment]
good for me. For now I will go with

```rb
require 'opal'
require 'opal_ujs'
#=require turbolinks
#=require_tree .
```

**Comment by elia** [comment]
Beware that as per sprockets rules comment-requires will only work at the top of the file. The first non-comment non-empty line will stop the parsing of comment-requires

**Comment by jibi** [comment]
well, if I use

```rb
#= require turbolinks                                                              
#= require_tree .
require 'opal'
require 'opal_ujs'
```

I get a `ReferenceError: Opal is not defined`, so I will just use sprockets rules and wait for the 0.8
(I guess because require_tree includes a controller_view.js.rb file before requiring Opal).

So I'll go with sprockets rules and wait for 0.8.

**Comment by elia** [comment]
> I guess because require_tree includes a controller_view.js.rb file before requiring Opal

That's correct

> So I'll go with sprockets rules and wait for 0.8.

:+1: hope it will be soon :)
