### ISSUE TITLE
Can't seem to get Opal working in Rails

### ISSUE THREAD

**Issue by erlingur** [opal/opal-rails#50]
I've created a barebones test project here: https://github.com/erlingur/opal-test

I've followed all of the instructions as best as I can see and where it falls down is the `puts "G'day world!"` line you have in the example of `app/assets/javascripts/greeter.js.rb`. My version just doesn't output anything to the console.

https://github.com/erlingur/opal-test/blob/master/app/assets/javascripts/home.js.rb

It's most likely just me misunderstanding the role Opal plays but I thought, according to the opal-rails docs, that this should work.

Any clues?

**Comment by elia** [comment]
Could be a bug on require_tree, can you ensure using require "home" actually works?

**Comment by erlingur** [comment]
Yup! Like usual when you finally give up and ask for help I got it working 5 minutes later :) Typical :)

So yeah, using `require 'home'` gets it working. `require_tree '.'` does not seem to work for me but `require_tree 'home'` will both load `app/assets/javascript/home.js.rb` AND `app/assets/javascript/home/index.js.rb`.

I've pushed a new version showing this:

https://github.com/erlingur/opal-test/blob/master/app/assets/javascripts/application.js.rb

**Comment by elia** [comment]
Ok then, closing in favor of https://github.com/opal/opal/issues/832

**Comment by erlingur** [comment]
Ok! I've got it running at least. :) Thanks for your help! :)

**Comment by erlingur** [comment]
Oh, also, Opal is seriously cool! Thanks for it! Love being able to write Ruby instead of JS :+1:

**Comment by elia** [comment]
I share the same feeling, props to @adambeynon who did the hard work! 🔨

**Comment by elia** [comment]
The `require_tree(".")` spec passes on opal@master so I'm adding a spec to opal-rails too in order to uncover the bug.

**Comment by elia** [comment]
https://github.com/opal/opal/pull/969 fixes the issue, keeping this open until it's merged.

**Comment by elia** [comment]
aaaand it's been merged! hooray!

**Comment by vais** [comment]
:tada:

**Comment by erlingur** [comment]
👏🏻
