### ISSUE TITLE
js.rb partials not served to xhr requests

### ISSUE THREAD

**Issue by kofno** [opal/opal-rails#52]
I was trying to use opal for SJR partials, but the js.rb partials aren't served to xhr requests.

Consider the following repo: https://github.com/kofno/opal_js_partial_fail

Run the server and visit the /foos resource. Clicking the link should present the js.rb template, which would trigger an alert. Instead, the html.erb template is served, which does nothing when fetch using xhr.

**Comment by elia** [comment]
Does it work using .js.opal as extension?

The rails template handler is registered only for that extension:

https://github.com/opal/opal-rails/blob/master/lib/opal/rails/template_handler.rb

**Comment by kofno** [comment]
Yes, that seems to work. Thanks!
