### ISSUE TITLE
ujs with opal

### ISSUE THREAD

**Issue by classyPimp** [opal/opal-rails#56]
Is it possible to use ujs with opal?
I required 'opal_ujs', but it's not working:
e.g.
  = link_to "search_pages", search_pages_path, onClick: "puts 'hello world!'" <== not working
  = link_to "search_pages", search_pages_path, onClick: "alert('hello world!')" <== everything ok

**Comment by elia** [comment]
Yes, ujs should word properly as all it does is requiring jquery_ujs internally. 

Passing "onClick" though is not supported as it directly writes the onClick attribute in the generated html. 

More on ujs: https://en.m.wikipedia.org/wiki/Unobtrusive_JavaScript
