### ISSUE TITLE
eval method not working

### ISSUE THREAD

**Issue by classyPimp** [opal/opal-rails#58]
eval method is not working, throws `Uncaught NoMethodError: undefined method `eval' for main`, tried bulding new apps, and on different machines with different versions.
edit:
e.g.
eval "alert 'FOO!'"
<====== excetion raised
eval "alert 'BAR'" <======this and further not executed
everything else works fine.

**Comment by classyPimp** [comment]
Asked question on stackovereflow didn't notice answer of mr. Elia Schito.
In case someone meets the issue

Kernel#eval is defined in opal-parser as it needs to be able to parse Ruby into JS in the browser, so you need to require "opal-parser" first.

Elia Schito

**Comment by elia** [comment]
😉
