### ISSUE TITLE
require executes module code

### ISSUE THREAD

**Issue by joostliketoast** [opal/opal-rails#61]
I Noticed that when I require a module that it already executes the code inside it

```ruby
module LittleHelper
  puts 'this is inside a module'
end
```

```ruby
require 'little_helper'

class ExampleClass
end

```

I wouldn't expect a message but it already displays the puts, even though I didn't do a include in the class yet.

**Comment by gabrielrios** [comment]
This is the expected on Ruby. When you require the file, the content gets read and "executed". 

You have the puts inside the module, so it will get executed as soon as the module get declared. If you don't want it, you have to wrap it on a method.

**Comment by elia** [comment]
As @gabrieleios said
