### ISSUE TITLE
template rendering error: IOError not opened for reading

### ISSUE THREAD

**Issue by theB264** [opal/opal-rails#64]
Anytime a `js.opal` template tries to render,
```
IOError at /test_opal
not opened for reading
```
from the first line of the template
`opal-rails 0.8.0`

**Comment by elia** [comment]
@theB264 can you please attach the full backtrace and error if you still have it available?

Does it work if you use `.js.rb` instead?

**Comment by theB264** [comment]
I am still looking into the issue; will advise one way or the other what is the cause

**Comment by theB264** [comment]
Okay, the issue here I found is that every instance variable object in the controller and any parent controllers (like `ApplicationController`) MUST respond to `.to_json`.  There was an instance variable in the parent controller that was raising an exception when to_json was called, and it was only happening once Opal was involved and began trying to render a template, because it needed to transfer its closure from Ruby to JSON.  The closure included an object that could not be converted to JSON.  As soon as I the method was overridden it works fine.
``` ruby
class<< @offending_object
  def as_json options= {}
    '{}'.freeze
  end
end
```
