### ISSUE TITLE
ERB opal partial is not working when using `locales`

### ISSUE THREAD

**Issue by razorcd** [opal/opal-rails#65]
I am rendering an Opal partial in my `index.html` using `erb` and `locales` variables.
`index.html.erb`:
```erb
<div id="element3-opal">From a .opal partial, with ERB `locals`, is NOT working!</div>
<script>
    <%= raw render :partial => "opal_partial2o.opal", formats: [:js],  handlers: [:erb],
                               locals: {localvar: "LOCAL VAR - opal"} %>
</script>
```
`opal_partial2o.opal`:
```ruby
Document.ready? do
  Element.find("#element3-opal").text("ERB and opal. localvar = `<%= localvar %>`")
end
```
RESULT:
```html
<div id="element3-opal">ERB and opal. localvar = `&lt;%= localvar %&gt;`</div>
```
But the `.opal` file is not processed by ERB (the `locales` variable are not inserted into the script).
I tried all solutions I could think of (renamed the files to .js .opal .erb ... , changed `handlers:` on the render, etc but nothing worked. I tried with Opal 0.7.1 and 0.8.

I made the same example using `coffee` + `erb` + `locales` and all worked fine:
```html
<div id="element3-coffee">ERB and coffee. localvar = `LOCAL VAR - coffee`</div>
```

I also made the same example using `Opal` + `haml` + `locales` and all worked fine:
```html
<div id="element3-opal-haml">HAML and opal. localvar = `LOCAL VAR - opal_haml`</div>
```

For my full example please refer to this PR:
https://github.com/razorcd/opal-rails-example/tree/adds_opal_test_details

Is this an Opal + ERB bug?

**Comment by gabrielrios** [comment]
I don't know if it should work with Opal+ERB but you can just use the local vars direct on opal and use string interpolation

```ruby
Document.ready? do
  Element.find("#element3-opal").text("ERB and opal. localvar = `#{localvar}`")
end
```

**Comment by razorcd** [comment]
Yes, you are right. Local vars are available directly in Opal!
This worked in the opal partial:
```opal
  puts localvar
  Element.find("#element3-opal").text("ERB and opal. localvar = `#{ localvar }`")
```

Thanks. Issue solved.

**Comment by elia** [comment]
📝 Just an additional note: keep in mind that local vars are passed to the template in JSON format, as specified in the README:

https://github.com/opal/opal-rails/blob/master/README.md#as-a-template
