### ISSUE TITLE
require Haml template file generates js Errors

### ISSUE THREAD

**Issue by joostliketoast** [opal/opal-rails#66]
I am having some problems getting templates to work.
When I require a template file the opal parser finds the file(as long as the extension is .haml and not .html.haml)
But it generates the following errors in js:

<img width="774" alt="developer_tools_-_http___localhost_3000_activiteiten_nieuw" src="https://cloud.githubusercontent.com/assets/5398047/9035773/47c856f2-39db-11e5-88dd-beba9207c83f.png">

following code in the initializer:
```ruby
Rails.application.config.assets.paths << Rails.root.join('app', 'views', 'shared').to_s
```

code in the haml file:
```haml
= link_to icon('bold'), '#', :class => 'btn btn-small toggle_bold'
= link_to icon('italic'), '#', :class => 'btn btn-small toggle_italic'
= link_to icon('link'), '#', :class => 'btn btn-small toggle_link'
```

required in application.js.rb:
```ruby
...
require 'opal'
require 'opal-haml'
require 'opal-jquery'
require '_textile_buttons'
...
```

Not really sure what i am missing here, that it's not working

**Comment by elia** [comment]
The haml process I should `require "template"` automatically but I'm not sure 100%; try doing it manually before requiring your haml file.

**Comment by joostliketoast** [comment]
the require didn't solve it. But i changed the opal-haml gem to the master branch and then it worked.
before it was release 0.3.0(which is the latest i believe)

So i think you already fixed the issue with the commit on march 19, but the gem needs a new release :)

**Comment by elia** [comment]
Thanks!

_I'll reopen to remind myself I need to release opal-haml_

**Comment by elia** [comment]
Done!

[opal-haml 0.4.0 is out](https://twitter.com/rubygems/status/636893085482532865)
