### ISSUE TITLE
Spring Support

### ISSUE THREAD

**Issue by wied03** [opal/opal-rails#69]
Once all of the work going on with opal-rspec 0.5 is complete, it might be useful to integrate spring support in. That way the Rake task can start up and the Rack process can stay loaded, allowing quick re-runs of specs using the Rake task.

**Comment by wied03** [comment]
Moved to https://github.com/opal/opal-rspec/issues/38

**Comment by wied03** [comment]
Never mind, Spring doesn't have a rails GEM dependency per se but it does seem to be fairly rails centric

**Comment by elia** [comment]
yep, we have to take a look at possible solutions and what other gems to, tho I'm sure it's fairly easy to add a binstub for opal stuff manually
