### ISSUE TITLE
problem with non-stupid-digest-assets gem and javascript_include_tag

### ISSUE THREAD

**Issue by joostliketoast** [opal/opal-rails#70]
I think I have found a problem with the javascript_include_tag helper method
it seems that the opal gem adds some code to it:

(redacted the src output with DOMAIN AND FILE for brevity)

``` ruby
"<script src=\"//[DOMAIN]/[FILE]-abd887fabfed639d6475aada7eef0724e9056f7bb0d519560ab17a925d48cd1.js\"></script><script>\n//<![CDATA[\n      if (typeof(Opal) !== 'undefined') {\n        Opal.mark_as_loaded(\"opal\");\nOpal.mark_as_loaded(\"widget/widget-agenda\");\nOpal.mark_as_loaded(\"rspec/matchers/built_in/have\");\nOpal.mark_as_loaded(\"diff/lcs\");\nOpal.mark_as_loaded(\"diff/lcs/hunk\");\nOpal.mark_as_loaded(\"fileutils\");\nOpal.mark_as_loaded(\"test/unit/assertions\");\nOpal.mark_as_loaded(\"coderay\");\nOpal.mark_as_loaded(\"optparse\");\nOpal.mark_as_loaded(\"shellwords\");\nOpal.mark_as_loaded(\"socket\");\nOpal.mark_as_loaded(\"uri\");\nOpal.mark_as_loaded(\"drb/drb\");\n        \n      }\n\n//]]>\n</script>"
```

And I think it conflicts with the non-stupid-digest-assets gem. 
Cause it now uses the digest file name instead of the non-digest file name that non-stupid-digest-assets normally generates.

I haven't been able to debug it further yet. 
But i hope someone knows what's going on, thanks.

**Comment by joostliketoast** [comment]
i think it has to do with this method:
https://github.com/opal/opal-rails/blob/a6b9a9b95c683e13b790e3c2e8186c565b240b0f/app/helpers/opal_helper.rb#L10

haven't dived in yet into what it does exactly

**Comment by elia** [comment]
_sorry for the delay_

You are right, opal-rails does add stuff to the `javascript_include_tag` method, namely it adds `Opal::Sprockets.load_asset` to bootstrap the main file, that's because opal files are compiled in load-able modules, and unless the main file is loaded nothing happens.

`opal-rails`' version uses super, so it should work with other modules/classes in the inheritance chain, can you check what `non-stupid-assets` do in that regard?

**Comment by elia** [comment]
@joostliketoast I think you can still disable the _digest_ by using Rails config (typically in `config/initializers/assets.rb`):

```rb
Rails.application.config.assets.digest = true
```

Let me know if that's enough.
