### ISSUE TITLE
Wrong content-type set for Opal responses when submitting a form remotely in rails

### ISSUE THREAD

**Issue by rainkinz** [opal/opal-rails#72]
I was trying a variation of this:

https://github.com/opal/opal-rails#as-a-template

to create a chat app example. When I submit a form 'remotely' using rails I get a response with the content-type set to 'text/html'. If I force the response type to be 'application/javascript' the app works as expected, i.e. from the example change this:

``` ruby
    render type: :js, locals: { messages_html: render_to_string(@message) }
```

to this:

``` ruby
render type: :js, content_type: 'application/javascript', locals: { messages_html: render_to_string(@message) }
```

I've created an example app https://github.com/rainkinz/messaging-with-faye that demonstrates the issue.

**Comment by elia** [comment]
I think the solution is to use `format: :js` instead of `:type` and/or `:content_type`, can you confirm?

If that holds true it's probably better to update the README to acknowledge that.

**Comment by rainkinz** [comment]
Unfortunately this didn't work. I messed round with the template handler a bit in a branch here:  

https://github.com/rainkinz/opal-rails/blob/force_content_type_in_template/lib/opal/rails/template_handler.rb

This makes it work, but I'm not sure if that is the correct approach.

**Comment by mibamur** [comment]
typescript example [typescript/rails/template_handler.rb](https://github.com/typescript-ruby/typescript-rails/blob/master/lib/typescript/rails/template_handler.rb)

coffee [coffee/rails/template_handler.rb](https://github.com/rails/coffee-rails/blob/master/lib/coffee/rails/template_handler.rb)

to @rainkinz @elia

**Comment by elia** [comment]
@rainkinz I added a spec to check for the correct content type, I know rails checks for secondary extensions (eg. `.html` in `foo.html.erb`) maybe that's enough to solve your problem.
