### ISSUE TITLE
Integrate `Opal.use_gem` in some way

### ISSUE THREAD

**Issue by Qqwy** [opal/opal-rails#73]
Opal now has a great feature to use gems in the front-end. From the command line, this can be done by writing `opal -g gemname your_source.js.rb > output.js`

When using the builder, one can use `Opal.load_gem "gemname"`. There does not seems to be a way to do this with opal-rails directly yet. 

I think the cleanest way would be to add a config option that accepts a list of gem names. Something like:

`config.opal.included_gems = %w(foo bar baz)`

**Comment by elia** [comment]
Just use `Opal.use_gem` somewhere during the initialization process, maybe it could be mentioned in the README (leaving the issue open for that).

Eg. you can add an `opal.rb` initializer in `config/initializers`.
