### ISSUE TITLE
Element.find('foo') or Element['foo'] finds only the first element on the page

### ISSUE THREAD

**Issue by Stormcore** [opal/opal-rails#74]
So it is not possible to make all elements handle some event.
Same for default generated example:

def all_links
    @all_links ||= element.find('a')
  end

def say_hello_when_a_link_is_clicked
    all_links.on :click do |event|
      # Use prevent_default to stop default behavior (as you would do in jQuery)
      # event.prevent_default

      puts "Hello! (You just clicked on a link: #{event.current_target.text})"
    end
  end

does not work at all

**Comment by Stormcore** [comment]
Issue solved-this only reproduces for multiple elements with same IDs

**Comment by elia** [comment]
:+1:
