### ISSUE TITLE
current javascript_include_tag prevents the use of async true in the script tag

### ISSUE THREAD

**Issue by elia** [opal/opal-rails#80]

**Comment by mibamur** [comment]
http://apidock.com/rails/ActionView/Helpers/AssetTagHelper/JavascriptTagHelpers/javascript_include_tag have no docs about it
but
http://stackoverflow.com/questions/35847281/how-do-i-load-page-javascript-after-async-loading-of-my-manifest-file
and 
http://stackoverflow.com/questions/10982375/add-defer-attribute-to-javascript-include-tag-rails
and
https://rhardih.io/2015/03/rails-4-gotcha-asynchronous-loading-of-javascript-in-development-mode/

**Comment by mibamur** [comment]
can we split async and defer javascript_include_tag group?
I think it is not bad idea, because HTTP2 is coming ;-)

**Comment by elia** [comment]
Fixed by v0.9.3

---

@mibamur the links you posted are definitely relevant to the issue, although despite the various rails-related gotchas it's good not to prevent users from using async because of opal 🙂
