### ISSUE TITLE
unreachable code after return statement

### ISSUE THREAD

**Issue by evjan** [opal/opal-rails#81]
When I try to run the [example](http://opalrb.org/docs/guides/master/rails.html) in my pre-existing Rails site I get the following error:

```unreachable code after return statement```

I click the link next to the error (**edit:** warning) and get the last line in this function highlighted:

```
def.$alias_method = function(newname, oldname) {
      var self = this;

      
      var newjsid = '$' + newname,
          body    = self.$$proto['$' + oldname];

      if (self.$$is_singleton) {
        self.$$proto[newjsid] = body;
      }
      else {
        Opal.defn(self, newjsid, body);
      }

      return self;
    
      return self;
    };
```

Using opal-rails 0.8.1 and Rails 4.2.5

**Comment by elia** [comment]
Is the error you get in the browser console or somewhere else?

Maybe this? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/return#Automatic_Semicolon_Insertion
…but in that case it would be a warning and not an error

Also that tutorial is outdated, I'll fix it soon-ish, but in the meanwhile please refer to the opal-rails readme form the `0-8-stable` branch: https://github.com/opal/opal-rails/tree/0-8-stable#asset-pipeline

**Comment by evjan** [comment]
Sorry, I wasn't clear. I get that error in the browser console and in Firefox.

**Comment by elia** [comment]
Ok, good then, if it's not blocking the execution it can just be ignored. I'll research if it's still the case with opal master. Thanks for reporting :)
