### ISSUE TITLE
Hamlit support instead Haml

### ISSUE THREAD

**Issue by mibamur** [opal/opal-rails#89]
Discussion start there https://github.com/k0kubun/hamlit/issues/77

**Comment by mibamur** [comment]
## Congratulations opal fans!

New opal gem is coming 

It's just conceptual and never tested.
https://github.com/hamlit/hamlit-opal

**Comment by elia** [comment]
Closing, since [hamlit-opal](https://github.com/hamlit/hamlit-opal) seems to be solving the issue

@mibamur please let me know if there's anything else that can be done for this on opal-rails
