### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by segantii-alex-falkowski** [opal/opal-rails#91]
Hi,

When will this be available?

Regards,
Alex

**Comment by mindaslab** [comment]
Oh, Rails 5 is not supported? I had some issues using opal-rails with Rails 5  app, thought the gem implementation was buggy :/

**Comment by elia** [comment]
I'm using Opal rails with rails 5 on a couple of apps, what errors did you encounter?

**Comment by segantii-alex-falkowski** [comment]
My bad must of had a look at the wrong version

https://rubygems.org/gems/opal-rails/versions/0.9.1 seems to support it. Apologies for the confusion.

**Comment by elia** [comment]
No problem thanks 🙂
