### ISSUE TITLE
use_gem causes error, can't start up

### ISSUE THREAD

**Issue by rangeoshun** [opal/opal-rails#98]
**Bugreport**

Hi!

I face an issue, which I could not resolve in two days now. Basic setup, I'd like to use a gem in my javascript asset. Namely Matrix, because I need Vectors. I'd like to share modules between the client and server, and would like to use same Ruby source, because the functionality is exactly the same, and would not like to maintain two copies, one in JS and one in Ruby.

Following docs I inserted configs, and a `use_gem` call:

```ruby
# config/initializers/assets.rb
# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'

# Add additional assets to the asset load path.
# Rails.application.config.assets.paths << Emoji.images_path
# Add Yarn node_modules folder to the asset load path.
Rails.application.config.assets.paths << Rails.root.join('node_modules')

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in the app/assets
# folder are already added.
# Rails.application.config.assets.precompile += %w( admin.js admin.css )

# Compiler options
Rails.application.config.opal.method_missing = true
Rails.application.config.opal.optimized_operators = true
Rails.application.config.opal.arity_check = !Rails.env.production?
Rails.application.config.opal.const_missing = true
Rails.application.config.opal.dynamic_require_severity = :ignore

Opal.use_gem 'matrix'
```

Just for sake of clearity I add that I created on route to load JS and have my `application.js.rb` `require 'matrix'`, but it does not really matter as the prue `use_gem` call will result in the error beneath.

```ruby
# Require the opal runtime and core library
require 'opal'

# For Rails 5.1 and above, otherwise use 'opal_ujs'
require 'opal_ujs'

# Require of JS libraries will be forwarded to sprockets as is
require 'turbolinks'

# a Ruby equivalent of the require_tree Sprockets directive is available
# disabled to avoid triple run of script
# require_tree '.'
require 'matrix'

puts "hello world!"
$$.console.log(Vector[0, 0])
```

After which I try to run server and receive this error:

```
$ rails server
=> Booting Puma
=> Rails 5.1.4 application starting in development
=> Run `rails server -h` for more startup options
Exiting
You've tried to invoke Spring when it's already loaded (i.e. the Spring constant is defined).

This is probably because you generated binstubs with Spring 1.0, and you now have a Spring version > 1.0 on your system. To solve this, upgrade your bundle to the latest Spring version and then run `bundle exec spring binstub --all` to regenerate your binstubs. This is a one-time step necessary to upgrade from 1.0 to 1.1.

Here's the backtrace:

/Library/Ruby/Gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/Library/Ruby/Gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
/Library/Ruby/Gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/Library/Ruby/Gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/Library/Ruby/Gems/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
/Users/range/Documents/opal-use_gem-issue/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
```

Git repo for reproduction: https://github.com/rangeoshun/opal-use_gem-issue.git

**Comment by elia** [comment]
I tried the test app (thank you!) just to realize you're actually trying to load not the `matrix` gem (may even not exist) but the `matrix` standard library! 

See: https://github.com/ruby/ruby/blob/389bda457a67409757a64ef62e53e5fc2c77dc02/lib/matrix.rb

Unfortunately there's no port/implementation of `matrix.rb` in the opal stdlib _yet_.

---

The way I'd proceed would be to just copy the `matrix.rb` file from the link above and paste it into my rails app and see how it behaves in opal. The result can vary from "just works" to "needs a couple of fixes" or in the worst case "needs complete reimplementation".

If you end up with anything usable I'd love to receive a PR to opal/opal adding it to the stdlib (if you need any guidance in doing that just let me know, I'd love to help).

_I'll close this, since looks like there's nothing wrong with `use_gem` but just a weird error in case the gem is not part of the bundle_

**Comment by rangeoshun** [comment]
Hey man!

Thanks for taking the time! You're right! I''l look into it, and if manage to come up with something useful, I'll make a PR.

If you can give me any guidelines how it should be done, please do so, and what I'm really not sure about is that do you guys cover these with tests? And if so, how? Should the transpiled JS be tested?

Cheers!

**Comment by elia** [comment]
@rangeoshun the main guide for hacking on opal including running specs [from the Ruby Spec Suite](https://github.com/ruby/spec) is this: https://github.com/opal/opal/blob/master/HACKING.md

I'm still available if anything isn't clear after reading it (we can always improve, especially in documentation) 😄

**Comment by rangeoshun** [comment]
@elia, I had a little time to play around with this, and seems the only issue I came across is the `def_e2message`, where this causes issues:
```ruby
  def bind(cl)
    self.module_eval "#{<<-"begin;"}\n#{<<-"end;"}", __FILE__, __LINE__ + 1
      begin;
        def Raise(err = nil, *rest)
          Exception2MessageMapper.Raise(self.class, err, *rest)
        end
        alias Fail Raise

        class << self
          undef included
        end
        def self.included(mod)
          mod.extend Exception2MessageMapper
        end
      end;
  end
```

Do you have some replacement message mapper implemented somewhere? So far I did not look into opal deep enough to find an other standard module that was ported and utilized this. If you recognize this problem would be a great help, but if not I investigate it further later.

Thanks!

**Comment by elia** [comment]
Got me sometime in order to parse visually the code above, after some experiments I found it's actually valid (yet weird) ruby. It's parsed correctly under opal@master (v0.11) but not in the latest release v0.10.5. 

Anyway this should be a safe (parsable) replacement:

```rb
def bind(cl)
  self.module_eval <<-RUBY, __FILE__, __LINE__ + 1
    def Raise(err = nil, *rest)
      Exception2MessageMapper.Raise(self.class, err, *rest)
    end
    alias Fail Raise

    class << self
      undef included
    end
    def self.included(mod)
      mod.extend Exception2MessageMapper
    end
  RUBY
end
```

There's still the problem that you can't eval strings unless you include the opal parser on the frontend, and it's advised not to do so as it's quite heavy, so in turn this should work as well:

```rb
def bind(cl)
  self.module_eval do
    def Raise(err = nil, *rest)
      Exception2MessageMapper.Raise(self.class, err, *rest)
    end
    alias Fail Raise

    class << self
      undef included
    end
    def self.included(mod)
      mod.extend Exception2MessageMapper
    end
  end
end
```

**Comment by rangeoshun** [comment]
Nice, and thank you man!

I'll give it a spin after finishing up websocket-rails port for the client side in opal. If all's working I'll do my due PR.
